name: ecnu_timetable
description: 更美观更智能的ECNU课程表。

# Prevent the package from being accidentally published to pub.dev.
publish_to: "none"

version: 0.8.0+12

environment:
  sdk: ">=2.15.0-172.0.dev"

dependencies:
  flutter:
    sdk: flutter
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  get:
  sentry_flutter:
  bottom_navy_bar:
  font_awesome_flutter:
  flutter_settings_screens: ">0.3.0"
  google_fonts:
  dio:
  flutter_spinkit:
  url_launcher:
  badges:
  flutter_markdown:
  loggy:
  flutter_loggy:
  flutter_loggy_dio:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  dependency_validator:
  flutter_launcher_icons:
  flutter_native_splash:
  flutter_app_name:

flutter_app_name:
  name: "ECNU Timetable"

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.otf
    - family: NotoSerifSC
      fonts:
        - asset: assets/fonts/NotoSerifSC-Regular.otf

  assets:
    - assets/images/
    - LICENSE
