name: ecnu_timetable
description: 更美观更智能的ECNU课程表。

# Prevent the package from being accidentally published to pub.dev.
publish_to: "none"

version: 0.4.0+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  get:
  sentry_flutter:
  bottom_navy_bar:
  font_awesome_flutter:
  logger:
  flutter_settings_screens: ">0.3.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  dependency_validator:
  flutter_launcher_icons:
  flutter_native_splash:
  flutter_app_name:

flutter_app_name:
  name: "ECNU Timetable"

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.otf
    - family: NotoSerifSC
      fonts:
        - asset: assets/fonts/NotoSerifSC-Regular.otf
