name: ecnu_timetable
description: 更美观更智能的ECNU课程表。

# Prevent the package from being accidentally published to pub.dev.
publish_to: "none"

version: 1.0.0+19

environment:
  sdk: ">=2.15.0-172.0.dev"

dependencies:
  flutter:
    sdk: flutter
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  get:
  sentry_flutter: ">=6.1.0-alpha.2"
  bottom_navy_bar:
  font_awesome_flutter:
  google_fonts:
  dio:
  dio_cookie_manager:
  cookie_jar:
  flutter_spinkit:
  url_launcher:
  badges:
  flutter_markdown:
  loggy:
  flutter_loggy:
  flutter_loggy_dio:
  dart_random_choice: ">=0.1.0-nullsafety.0"
  path_provider:
  universal_html:
  cached_network_image:
  quiver:
  hive_flutter:
  flutter_settings_screens: ">0.3.0"
  json_annotation: ">=4.3.0"
  flutter_layout_grid:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  dependency_validator:
  flutter_launcher_icons:
  flutter_native_splash:
  flutter_app_name:
  hive_generator:
  build_runner:
  json_serializable:
  msix:

flutter_app_name:
  name: "ECNU Timetable"

msix_config:
  display_name: "ECNU Timetable"
  publisher_display_name: "CCXXXI"
  identity_name: "io.github.ccxxxi.ecnu-timetable"
  msix_version: 1.0.0.19
  logo_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.otf
    - family: NotoSerifSC
      fonts:
        - asset: assets/fonts/NotoSerifSC-Regular.otf

  assets:
    - assets/images/
    - LICENSE
