name: check

on:
  push:
  pull_request:
  schedule:
    - cron: '10 16 * * FRI'

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [ stable, beta, dev, master ]
    steps:
      - uses: CCXXXI/flutter-action@main
        with:
          channel: ${{ matrix.channel }}

      - run: flutter analyze

  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [ stable, beta, dev, master ]
    steps:
      - uses: CCXXXI/flutter-action@main
        with:
          channel: ${{ matrix.channel }}

      - run: flutter test --coverage
      - uses: codecov/codecov-action@v2

  dependency_validator:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [ stable, beta, dev, master ]
    steps:
      - uses: CCXXXI/flutter-action@main
        with:
          channel: ${{ matrix.channel }}

      - run: flutter pub run dependency_validator
