name: build

on:
  push:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: CCXXXI/flutter-action@main
      - run: sudo snap install flutter --classic

      - run: flutter build linux

      - uses: papeloto/action-zip@v1
        with:
          files: build/
          dest: linux-build-test.zip
      - uses: actions/upload-artifact@v2
        with:
          name: linux-build-test
          path: linux-build-test.zip
