name: build

on:
  push:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: CCXXXI/flutter-action@main

      - run: flutter build ios --no-codesign
      - run: flutter build macos

      - uses: papeloto/action-zip@v1
        with:
          files: build/
          dest: macos-build-test.zip
      - uses: actions/upload-artifact@v2
        with:
          name: macos-build-test
          path: macos-build-test.zip
